name: Remove waiting-response label

on: [issue_comment]

jobs:
  remove_label:
    if: github.actor != 'cyrilgdn'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["waiting-response"]
            })
