name: test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pgversion: [16, 15, 14, 13, 12, 11]

    env:
      PGVERSION: ${{ matrix.pgversion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: test
        run: make test

      - name: vet
        run: make vet

      - name: testacc
        run: make testacc
