name: test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pgversion: [17, 16, 15, 14, 13, 12]

    env:
      PGVERSION: ${{ matrix.pgversion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.15.4'
          terraform_wrapper: false

      - name: test
        run: make test

      - name: vet
        run: make vet

      - name: testacc
        run: make testacc
