name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pgversion: ["latest", 12, 11, 10, 9]

    env:
      PGVERSION: ${{ matrix.pgversion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: test
        run: make test

      - name: vet
        run: make vet

      - name: testacc
        run: make testacc
