name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pgversion: [16, 15, 14, 13, 12]

    env:
      PGVERSION: ${{ matrix.pgversion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
          terraform_wrapper: false

      - name: test
        run: make test

      - name: vet
        run: make vet

      - name: testacc
        env:
          TF_ACC_TERRAFORM_PATH: ${{ steps.setup-terraform.outputs.terraform-path }}
        run: make testacc
